version: "3.3"

services:

  mongodb:
    image: 'mongo:latest'
    ports:
    - "27017:27017"
    networks:
    - appnet

  public:
    build: './public'
    ports:
      - '4400:4400'
      - '49153:49153'
    volumes:
      - './public:/usr/src/app'
    depends_on:
      - mongodb
    networks:
      - appnet

  server:
    build: './server'
    ports:
      - '5400:8000'
    volumes:
      - './server:/home/node/server'
    depends_on:
      - mongodb
    networks:
      - appnet

networks:
  appnet: