version: '3.3'

services:

  mongodb:
    build: ./database/mongodb
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - dbnet

  server:
    build: ./server
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - appnet
      - dbnet
    ports:
      - '3000:3000'
    volumes:
      - ./server:/home/node/server

  public:
    build: ./public
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - appnet
      - dbnet
    ports:
      - '4200:4200'
    volumes:
      - ./public:/usr/src/app

networks:
  appnet:
  dbnet: